export const iconMap = {
  AC: 'icon_equip_ac',
  TV: 'icon_equip_tv',
  bathroom: 'icon_equip_bathroom',
  engine: 'icon_equip_engine',
  gas: 'icon_equip_gas',
  kitchen: 'icon_equip_kitchen',
  microwave: 'icon_equip_microwave',
  radio: 'icon_equip_radio',
  refrigerator: 'icon_equip_refrigerator',
  water: 'icon_equip_water',
  transmission: 'icon_equip_transmission',
  van: 'icon_type_panelTruck',
  fullyIntegrated: 'icon_type_fully_integrated',
  alcove: 'icon_type_alcove',
};
